name: Python application
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_KEY: '${{ secrets.API_KEY }}'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install requests
      - name: test
        run: |
          pytest Demo.py
